sudo: required

language: python

services:
  - docker

before_install:
- docker pull billmills/cat-icecream

script:
- docker run -v $PWD:/cat-icecream billmills/cat-icecream /bin/bash -c "cd /cat-icecream; nosetests tests/*.py"
